### ISSUE TITLE
Bug firefox doNotTrack

### ISSUE THREAD

**Issue by Ditwo** [CNILlab/Cookie-consent_Google-Analytics#6]
Bonjour,
Je me rends compte que la fonction notToTrack() renvoie toujours "true" sous Firefox  (35.0), quel que soit le réglage Pistage. Firefox ne semble pas mettre à jour les changements d'option. 

navigator.doNotTrack renvoie donc toujours "yes". 
Le trafic n'est pas comptabilisé de ce fait.

Je propose de tester si le navigateur est Firefox dans cette fonction : 

function notToTrack()
{
/* aw - bug firefox renvoie navigator.doNotTrack = "yes" quel que soit le reglage du pistage*/
var is_firefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1; //true si firefox
        if ( (!is_firefox && navigator.doNotTrack && (navigator.doNotTrack=='yes' || navigator.doNotTrack=='1'))
            || ( navigator.msDoNotTrack && navigator.msDoNotTrack == '1') ) {
            var isIE = (getInternetExplorerVersion()!=-1)
            if (!isIE){    
                 return true;
            }
            return false;
        }
 }

Cordialement
Ditwo

**Comment by vtoubiana** [comment]
Bonjour,
Je ne rencontre pas ce probléme, êtes vous sur que la valeur de DNT envoyée par votre navigateur est bien "0"? Il se peut qu'une extension interfére et modifie la valeur de DNT configurée dans Firefox.

Bien cordialement,

Vincent
