### ISSUE TITLE
Le code ne fonctionne pas

### ISSUE THREAD

**Issue by pixels-aromates** [CNILlab/Cookie-consent_Google-Analytics#9]
J'ai copier/coller votre code en changeant correctement le code de suivi. Le message s'affiche bien mais google analytics continue de tracker les visites lorsque l'on s'y oppose. Le site  en question : http://www.retraite.verspieren.com/ . Pouvez-vous m'indiquer si il y a un souci.

Merci

**Comment by vtoubiana** [comment]
Bonjour,
En fait le code enregistre l'optout pour le domaine "retraite.verspieren.com" hors votre code Google Analytics est appelé depuis le domaine "verspieren.com". 
J'ai modifié le code pour que vous puissiez spécifier le domaine dans la varabile domainename (initialement égale à ''). Vous n'avez qu'à remplacer cette valeur par "verspieren.com" et ça devrait fonctionner.

Je garde le probléme ouvert en attendant que vous me signialiez si le problème est résolu.

Merci,

Vincent

**Comment by pixels-aromates** [comment]
Bonjour Vincent,

Merci pour votre réponse et votre réactivité. J'ai essayé en mettant comme valeur à la variable "verspieren.com" et "www.verspieren.com". Sans succès malheureusement...

**Comment by vtoubiana** [comment]
Bonsoir,

Pourriez vous remettre la valeur à "verspieren.com" pour que je puisse effectuer un test?

Merci.

**Comment by pixels-aromates** [comment]
Bonjour Vincent,

J'ai remis "verspieren.com".

Merci!

**Comment by Thibault34** [comment]
Bonjour,
Je viens de regarder votre site, mais je ne vois pas le bandeau d'avertissement.

Pour ma part, je dispose d'un site en sous domaine aussi (ou je fais mes tests : http://beta.maths-andreossy.fr/)

Je viens de faire faire une mise à jour (qui posais ce problème), les utilisateurs qui refusaient les cookies et qui ensuite naviguaient sur le site se voyaient quand même suivi...

Je vous conseil de prendre la dernière version, qui date de quelque heures et aussi, sois de mettre votre domaine dans la variable sois de modifier
ga('create', gaProperty, 'auto');
par
ga('create', gaProperty, getDomainName());


Bien à vous

**Comment by pixels-aromates** [comment]
J'avais une erreur javascript dans mon code. J'ai remplacer ga('create', gaProperty, 'auto');
par ga('create', gaProperty, getDomainName()); Ca ne marche pas non plus.

**Comment by Thibault34** [comment]
Vous avez bien pris la mise à jour d'aujourd'hui ?

**Comment by pixels-aromates** [comment]
Ca a l'air de fonctionner désormais! Merci pour votre disponibilité!
